### PR TITLE
Convert testbed app to support test mode

### PR DESCRIPTION
**Pull request by freakboy3742**
Converts the testbed app to a stub app with a pytest test suite, able to be run with `briefcase run --test`.

Converts the testbed app itself into the barest stub that will actually start. It doesn't use a GUI framework - it uses bare platform APIs. The tests have all been moved to the tests folder, and converted to pytest instead of the ad-hoc testing framework.

Takes the opportunity to add pre-commit with black etc processing.

Needs the briefcase test branch (Refs https://github.com/beeware/briefcase/pull/962), plus the various `testcase2` template branches to work. The CI and project configurations have been modified to use those branches; those modifications will need to be removed before this is merged.

Includes a CI configuration that runs the project to confirm that it works.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by rmartin16** [comment]
FWIW, the test suite successfully completes on my machine. Also, I noticed the 3.11 support package is using Python `3.11.0b3`.

**Comment by freakboy3742** [comment]
> FWIW, the test suite successfully completes on my machine. Also, I noticed the 3.11 support package is using Python `3.11.0b3`.

Out of interest - what OS/version combination are you running? And which OS are you seeing the 3.11.0b3 support package on?

**Comment by rmartin16** [comment]
OS Info
I'm running Pop!_OS 22.04 (an Ubuntu derivative).
```
✦ ❯ uname -a
Linux jupiter 6.0.6-76060006-generic #202210290932~1667401208~22.04~d2df702 SMP PREEMPT_DYNAMIC Wed N x86_64 x86_64 x86_64 GNU/Linux

~ 
✦ ❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
```

I'm seeing Python version `3.11.0b3` in the [Linux 3.11 support package](https://briefcase-support.s3.amazonaws.com/python/3.11/linux/x86_64/Python-3.11-linux-x86_64-support.b1.tar.gz).

**Comment by freakboy3742** [comment]
Huh... looks like I neglected to publish a 3.11.0 version when I updated all the tags for 3.11. I'll fix that on Monday (along with working out why the AppImage 3.11 build is failing when importing `sre`...)

**Review by mhsmith — APPROVED** [review]

**Pull request merged**
